language: node_js
node_js:
  - "stable"
env:
  - MONGO_HASH=mongodb+srv://bianca:bianca@cluster0.zgi7m.mongodb.net/sampledb?retryWrites=true&w=majority
services:
  - mongodb
script:
  - npm ci
  - npm run test
notifications:
  email: false
