language: node_js
node_js:
  - "stable"
env:
  global:
    - MONGO_HASH="mongodb+srv://bianca:bianca@cluster0.zgi7m.mongodb.net/sampledb?retryWrites=true&w=majority"
    - CLOUDINARY_NAME='bn47'
    - CLOUDINARY_API_KEY='849371263484589'
    - CLOUDINARY_API_SECRET='SlQBSPsWlUH8FPdPi6DWH7d7KRs'
services:
  - mongodb
script:
  - npm ci
  - npm run test
  - npm run coverage
notifications:
  email: false
